### ISSUE TITLE
Add instrument to datasets

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#104]
One important piece of info that we're still missing for each dataset is which telescope/instrument did the observation. I would like to add this to every dataset in `input/data` now.

What should we use as key? Maybe "telescope" or "instrument"?
For values, we already have a list of strings we use elsewhere:
```
enum: [hess, veritas, magic, whipple, hegra, cangaroo, hawc, milagro, crimea, argo]
```
https://github.com/gammapy/gamma-cat/blob/master/input/schemas/basic_source_info.schema.yaml#L35

Where should we put the info?
I would say in each input file (i.e. ECSV, YAML).
But before we've already discussed a per-dataset (i.e. usually per-paper) `info.yaml`.

Since I'll go through anyways and add this info everywhere, while I'm at it I could also add other info if needed.

@GernotMaier - Thoughts?

**Comment by GernotMaier** [comment]
I think either of the names (telescope / instrument) are fine.

We should put it in each file; as there are multi-instrument papers where maybe the SED is only from one instrument, but all other results from both.

**Comment by cdeil** [comment]
I'll go with the keyname "telescope", because in FITS OGIP they use `TELESCOP` for this (due to the 8 char limitation for FITS headers that we don't have here.

**Comment by cdeil** [comment]
This is implemented in master.

So far, there was only one paper with two "telescopes": `2014ApJ...780..168A`

@GernotMaier - Could you please review if this is correct:
https://github.com/gammapy/gamma-cat/commit/dc8aa92bfacf53072ffc9088c91f252a758b0300

Specifically, is it correct that `tev-000030-1-lc.ecsv` is "hess", whereas `tev-000030-1-sed.ecsv` and `tev-000030-1.yaml` are "veritas"?

**Comment by cdeil** [comment]
@GernotMaier - I now saw that you had already added "observatory" keys for the datasets you had entered. I've removed those, because it was now duplicated info with the "telescope" key. Also there was a mistake where I had put "hess" instead of "veritas".

Fixed in master in 541e37b .

Should now all be good.
Closing this issue now.

Of course, if there's something else to correct or add, please open an issue or pull request.

**Comment by GernotMaier** [comment]
All looks good.

- observatory key can go

- lc and sed keys are not related: light curves are one for HESS and one for VERITAS (counter 1 and 2); seds are for different phase ranges, and the counter correspond to the counter of the yaml files. I see that this might be confusing - do you know of a way to do it better?

**Comment by cdeil** [comment]
> I see that this might be confusing - do you know of a way to do it better?

I don't have a better idea. It's OK now, and if you, me or someone has a better idea in the future, we can always file an issue or PR and make it better. Some things become clear with time (e.g. that we're missing "telescope" in each dataset, oops) :-)
