### ISSUE TITLE
ZeroDivisionError from uncertainties in energy flux computation

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#107]
CI is broken (has been for weeks) on travis-ci:
https://travis-ci.org/gammapy/gamma-cat/builds/224975711#L663

It's a ZeroDivisionError from uncertainties in energy flux computation, with Anaconda on Python 3.5 or 3.6.

I haven't been able to reproduce it locally, not even with Anaconda.

@adonath - Could you try, please, by executing the commands here?
https://github.com/gammapy/gamma-cat/blob/master/.travis.yml

**Comment by adonath** [comment]
I was able to reproduce the issue locally on my machine. It seems the error is related to the fact, that the index for source 94 (HESS J1708-443) is *exactly* `index=2`, which is handled as a special case in `Powerlaw.energy_flux()` but not in `Powerlaw.energy_flux_error()`. The solution here is probably to reimplemented analytical solutions for `.integral_error()` and  `.energy_flux_error()` for the simple cases, where the solutions are known (`Powerlaw` and `Powerlaw2`). I'll make a gammapy issue for that....

**Comment by cdeil** [comment]
@adonath - Can you please make this work now?

This should work and only take little time?
- add a regression test for the spectral index = 2.0 case
- commenting out  the special case for `Powerlaw.energy_flux`
- make the reminder issue that the special cases should be brought back when someone has time.

**Comment by adonath** [comment]
Yes, I can try work on that now. Just to make it clear: that solution is to **add** the special case to `.energy_flux_error()`and not to remove it from `Powerlaw.energy_flux`...

**Comment by cdeil** [comment]
As you like. Implementing special analytical cases is something that will take time. It's also something that can be distributed to others that have experience with it and know where to look up the formulae (e.g. I spent several days finding and debugging the formulae in HAP, and Julien did it for START). That's way I was suggesting to put a quick fix for now.
