### ISSUE TITLE
Relation to CDS, SIMBAD, VIZIER

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#11]
@GernotMaier suggested to look into the possibility to use SIMBAD or VIZIER from [CDS](http://cds.u-strasbg.fr/) instead of making a separate project.

E.g. some of the VERITAS data is found / available there:
http://simbad.u-strasbg.fr/simbad/sim-id?Ident=VER&NbIdent=cat&Radius=2&Radius.unit=arcmin&submit=submit+id

Most TeV data isn't available there though, and I'd be surprised if they want it all there.
It needs someone to collect, reformat and maintain it for every existing and future publication.

However, we should talk to them and at least interoperate as much as possible (e.g. on source identifiers) and document on our side what is available at CDS and how to find it.

**Comment by cdeil** [comment]
@GernotMaier  I've written up a first draft of the `gamma-cat` ADASS proceeding:

https://github.com/gammapy/adass2016-gamma-cat-poster/blob/master/paper/P6-7.pdf

I currently have this:

> SIMBAD and Vizier at CDS are collections of all astronomical objects. They do contain information on TeV gamma-ray sources, e.g. a list of H.E.S.S. sources known to SIM- BAD is at http://simbad.u-strasbg.fr/simbad/sim-id?NbIdent=cat&Ident= HESS. However, with SIMBAD it’s currently not easy to get a list of gamma-ray sources, and they don’t have detailed information on the gamma-ray sources, e.g. morphology information, spectral point or lightcurve data.

For me it's hard to see how SIMBAD and Vizier could be a working solution to collect TeV gamma-ray data at this point. A separate project driven by gamma-ray astronomers, with community feedback about what data / formats are wanted, iterating on the data archive and formats for a while seems best.

@GernotMaier @cboisson - Do you agree? Or do you think pursuing a collaboration with CDS at this time, trying to get them to add more information on TeV sources as well as TeV spectra and lightcurves makes sense?

**Comment by GernotMaier** [comment]
We had a discussion on this on VERITAS, and will now build a VERITAS source catalogue at HEASARC (pre-discussion have taken place with them). 

This is certainly kind of orthogonal to your effort, although it will give exactly what you want: open access in a clearly defined format. The latter will be FITS, but the details have to be discussed with HEASARC. This will also give gamma-cat free and easy access to all published high-level VERITAS results.

**Comment by cboisson** [comment]
Dear Christoph,

Your statement on  Vizier and  SIMBAD is misleading.

SIMBAD is a collection of all sources published in refereed papers (with 
x-check of names) giving the basic informations and the thorough 
bibliography.

Vizier is a compilation of all published catalogs with access to the 
data that are in. For papers published in A&A it is now compulsory to 
give the content of your tables and data points to be attached. The 
paper is then considered by Vizier. For other journals it is on a good 
will basis.

This beeing said, I think there are 2 aspects to  the question you are 
asking.

It is certainly worth pursuing asking CDS to add more info on sources, 
as well as allow to dig them easily out in a uniform way (they have done 
a good job recently with photometric data).That can be discussed next 
week with the actors during the ADASS meeting.

The other thing is to have a dedicated "gamma" catalog, in a format that 
best suit us, with even more information. This will not have the same 
usage and in any case can be linked to Vizier (if it is an open catalog 
with a url link).

Cheers, Catherine


<https://www.mpi-hd.mpg.de/hfm/HESS/pages/publications/auxiliary/auxinfo_SNRG349>

**Comment by cdeil** [comment]
@cboisson - I submitted the pre-conference version for ADASS an hour ago:
https://github.com/gammapy/adass2016-gamma-cat-poster/releases
As far as I know it's not circulated anywhere, it's just for the editors to judge the number of contributions they will have?

I expect `gamma-cat` to make much progress in the coming weeks, and we'll get feedback at ADASS and the CTA meeting, and then we'll write a better proceeding until November 20th which better reflects the different projects and how gamma-cat fits in.

OK?

@GernotMaier - It would be nice if data format and data collection efforts aren't duplicated. So if you think it's worth talking to someone from VERITAS or HEASARC working on this, please point them to https://github.com/gammapy/adass2016-gamma-cat-poster/blob/master/adass2016-gamma-cat-poster.pdf and put us in touch via email.

**Comment by cboisson** [comment]
Le 14/10/2016 à 11:46, Christoph Deil a écrit :
>
> @cboisson <https://github.com/cboisson> - I submitted the 
> pre-conference version for ADASS an hour ago:
> https://github.com/gammapy/adass2016-gamma-cat-poster/releases
> As far as I know it's not circulated anywhere, it's just for the 
> editors to judge the number of contributions they will have?
>
> I expect |gamma-cat| to make much progress in the coming weeks, and 
> we'll get feedback at ADASS and the CTA meeting, and then we'll write 
> a better proceeding until November 20th which better reflects the 
> different projects and how gamma-cat fits in.
>
> OK?
>
Fine.
>
> @GernotMaier <https://github.com/GernotMaier> - It would be nice if 
> data format and data collection efforts aren't duplicated. So if you 
> think it's worth talking to someone from VERITAS or HEASARC working on 
> this, please point them to 
> https://github.com/gammapy/adass2016-gamma-cat-poster/blob/master/adass2016-gamma-cat-poster.pdf 
> and put us in touch via email.
>
It is indeed relevant to CTA as well. There is also discussions on how 
to build a CTA source catalog.
You can have a look at a document we circulated in PHYS last July:
https://portal.cta-observatory.org/recordscentre/_layouts/DocIdRedir.aspx?ID=CTADOC-383-584&hintUrl=Records/DATA/DATA-PIPE/CTA_SourceCatalog_v1.0.pdf

**Comment by GernotMaier** [comment]
Agreed (and I am part of the VERITAS effort).

**Comment by cdeil** [comment]
I'm closing this old issue discussing the relationship of gamma-cat to CDS, SIMBAD, VIZIER .

There isn't much overlap in the data collection or scope, and I think there is agreement that it's good to have gamma-cat as a separate project, trying to integrate it at CDS doesn't seem possible / useful to me.

@GernotMaier - Is the separate VERITAS / HEASARC effort still alive? If yes, would it make sense to have a short call to exchange ideas / look for possible collaboration to avoid duplicated effort?

There has been a lot of progress on gamma-cat in the past months, and we should really make an effort to expose the data and status at https://gamma-cat.readthedocs.io/index.html . I'll try to find time to work on this, but I'm not sure I will ...
