### ISSUE TITLE
Use units more in input files

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#112]
This is a reminder issue, under the 1.0 milestone.

Currently in our input files (both YAML and ECSV) we use a mix of numbers with default units, and of strings that can be parsed (usually by `astropy.units.Quantity`): https://github.com/gammapy/gamma-cat/blob/master/input/schemas/dataset_source_info.schema.yaml

In  https://github.com/gammapy/gamma-cat/pull/110#discussion_r113274953 @GernotMaier commented
> I would prefer to write explicitly everywhere the units. It makes it more transparent and doesn't require any insider knowledge.

I like the short style of just numbers with default units in some cases (typing `cm-2 s-1 TeV-1` many times can become tedious) but generally I agree that we should use units more (maybe even everywhere).

If anyone wants to help out with this, my suggestion would be to do it one key / easy to review pull request at a time.
E.g. in the schema change
```
      livetime:
        type: number
        unit: hour
        description: Livetime
```
to 
```
      livetime:
        type: string
        description: Livetime quantity (e.g. "42 hour")
```
and then fix all cases using your favourite search & replace tool (I use PyCharm -> Search Path and sometimes `ack`).

**Comment by pdeiml** [comment]
Can you leave a list with all quantities that should be changed here?
What about e.g. significance which does not have a unit?

**Comment by cdeil** [comment]
> Can you leave a list with all quantities that should be changed here?

I'm not sure. Not many.

One TODO I see in the spec is to make the `erange` entries uniform:
https://github.com/gammapy/gamma-cat/blob/master/input/schemas/dataset_source_info.schema.yaml#L229

Looks like we currently have these two cases:
```
input/data/2016/2016arXiv161101863H/tev-000039.yaml
34:  erange: {min: 0.316, max: 30}

input/data/2016/2016MNRAS.459.2550A/tev-000105.yaml
23:  erange: {min: 0.21, max: 0.42, unit: TeV}
```
I guess the options we have are either number, number, unit:
```
 erange: {min: 0.21, max: 0.42, unit: TeV}
```
or string, string like
```
 erange: {min: 0.21 TeV, max: 0.42 TeV}
```
I don't have a preference. But if you tough this (in a new PR), please make sure the code lines processing that key (which you can find with `ack erange gammacat`) properly handle the input and units and give a correct catalog as output.

> What about e.g. significance which does not have a unit?

If it ain't broken, don't fix it.

---

@pdeiml - If you have significant time (many hours) to work on gamma-cat, that would be great, then we should Skype and I could describe an important improvement / change to you (the morphology model entry format in the YAML files should be improved, to be similar to what we now have for spectral models, a change I made a few months ago for the input format).

**Comment by cdeil** [comment]
I think our input files / schemas now have units for most things. Closing this old issue.

There might be a few more quantities where changing the input format or adding unit info would be useful. So pull requests to improve the input files still welcome. But IMO it's low priority; we're already pretty well-organised, and have much more important work to do: expose the data via the gamma-cat and gamma-sky.net webpages, make it accessible via gammapy.catalog; data entry.
