### ISSUE TITLE
Add spectrum index to light curves

### ISSUE THREAD

**Issue by GernotMaier** [gammapy/gamma-cat#113]
Some bright blazar publications include spectrum indexes calculated in short times in the publications (e.g. 1611.04626) and should be part of the light curve. E.g.

MJD Flux>560GeV Flux Error >560GeV index dindex flux from fit >0.4 TeV flux error from fit >0.4 TeV
56780.15070072 2.792592219089e-06 3.317025298029e-07 -2.33432e+00 1.60595e-01 1.265944e-06 1.87904e-07
56780.15764517 2.890047801893e-06 3.468261023163e-07 -2.39124e+00 1.66283e-01 1.144892e-06 1.755768e-07
...

Can we add index (and its error) to the light curve schemes?

**Comment by cdeil** [comment]
@GernotMaier - OK.

There is no lightcurve format defined yet at `gamma-astro-data-formats`.
For now, we have an informal description here:
https://github.com/gammapy/gamma-cat/blob/master/input/schemas/lightcurve-format.md

Feel free to add something and just mention it there.

**Comment by GernotMaier** [comment]
see updates:

- added new variables index and index_error to light-curve scheme
- added data from 2017ApJ...834....2A: light curves with index spectral index

**Comment by cdeil** [comment]
@GernotMaier - Thanks!

I've changed the sign convention to be consistent with what we have in the YAML files for spectral index in 40d7281 .

Closing this now.
