### ISSUE TITLE
Support papers with multiple datasets

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#124]
This is a reminder issue for myself to add support for papers with multiple datasets (ECSV or YAML files). E.g. for SEDs we have these, and only one of the given SEDs is copied to the output folder:
```
docs/data/data/2010A%26A...516A..62A/gammacat_2010A%26A...516A..62A_000074_sed.ecsv
docs/data/data/2014ApJ...780..168A/gammacat_2014ApJ...780..168A_000030_sed.ecsv
docs/data/data/2016arXiv161003751S/gammacat_2016arXiv161003751S_000030_sed.ecsv
docs/data/data/2017ApJ...834....2A/gammacat_2017ApJ...834....2A_000049_sed.ecsv
```

**Comment by pdeiml** [comment]
I think that this issue can be closed, can't it? We already have multiple seds etc. in the output folder.

**Comment by cdeil** [comment]
Yes. I think I opened this issue before we had a file / folder structure where there can be multiple datasets in the output folder. So this is resolved.
