### ISSUE TITLE
Fix SED files for 2017ApJ...834....2A

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#125]
@GernotMaier - I see you've recently added data for 2017ApJ...834....2A :
https://github.com/gammapy/gamma-cat/commit/e857e52fd178d609afa16561bb9d99a94f7f5d4d#diff-313fd65c5acba69d74920406ac587fa5

The SED file has columns `dnde`, but units of `TeV m-2 s-1`.

We use column name `e2dnde` if the fluxes are given as `E^2 dN/dE`, and `dnde` for `dN/dE`.

Could you please double-check whether these are `dnde` or `e2dnde` fluxes and what the units are, and either correct the column names or the units in those two SED files?

**Comment by cdeil** [comment]
Actually I've gone ahead and changed to `e2dnde` in 93a72ac (because this was causing an error and blocking me to work on gamma-cat).

@GernotMaier - Can you confirm that this was the correct fix? Or was id `dnde` fluxes after all and the units were incorrect?

**Comment by GernotMaier** [comment]
It was e2dnde, thanks for that.
