### ISSUE TITLE
Checking consistency of reference_id in /input/data and /input/sources

### ISSUE THREAD

**Issue by pdeiml** [gammapy/gamma-cat#126]
This is a short reminder issue about an idea Christoph and me discussed.

It would be nice to have a script which checks whether all reference_id which occur as folders in /input/data/ are listet in the files in /input/sources.
(One could add it to the "make.py check" procedure instead of having a standalone script).

**Comment by cdeil** [comment]
Yes, it's a good idea. Code should go here: https://github.com/gammapy/gamma-cat/blob/0b5f5de58a04bd83e3df3faba1d4a448f9777e61/gammacat/checks.py#L88

General comment: There's still several days of coding / many improvements to be done for gamma-cat. Pull requests welcome any time. (But the gamma-cat code / scripts are not very easy to get into / takes some Python experience.)

**Comment by pdeiml** [comment]
I close this issue because it is implemented in 
https://github.com/gammapy/gamma-cat/issues/156
