### ISSUE TITLE
Correct reference for lightcurve: 2008ApJ...679.1427A or 2011ApJ...738....3A ?

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#128]
In https://github.com/gammapy/gamma-cat/pull/127#issuecomment-307354776 @pdeiml noticed that the lightcurve file at https://github.com/gammapy/gamma-cat/blob/master/input/data/2011/2011ApJ...738....3A/tev-000014-lc.ecsv contains `reference_id: 2008ApJ...679.1427A` which doesn't match the folder name.

Note that there is already a lightcurve file at 2008ApJ...679.1427A, but it looks like it's content is different:
https://github.com/gammapy/gamma-cat/blob/master/input/data/2008/2008ApJ...679.1427A/tev-000014-lc.ecsv

@GernotMaier - Can you please comment which is correct? 
(or if you have time, make a pull request directly with the correct fix, and if there are multiple LC files in 2008ApJ...679.1427A, please add a comment to all which is which, i.e. how they correspond to the paper)

**Comment by GernotMaier** [comment]
The correct reference for this file is 2011ApJ...738....3A

**Comment by cdeil** [comment]
@GernotMaier - Thanks!
Fixed in 1d39ab5 .
