### ISSUE TITLE
pip install regions fail on travis-ci

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#133]
The gamma-cat build is failing on travis-ci and RTD now:
* https://travis-ci.org/gammapy/gamma-cat/builds/253190303#L365
* https://readthedocs.org/projects/gamma-cat/builds/5683433/

@bsipicz - Do you understand why? I think this is an issue that was fixed in astropy-helpers, but it still shows up in the older `regions` 0.2 release? Does that mean we need to do a bugfix release for `regions` and possibly other packages?

**Comment by cdeil** [comment]
@pdeiml ran into the same issue and reported it via email.

This was discussed at length in https://github.com/sphinx-doc/sphinx/issues/3766 and https://github.com/astropy/astropy-helpers/issues/302#issuecomment-305976972 but I don't remember how it was fixed. This now works for me with Python 3.6 the existing regions 0.2 release and Sphinx 1.6.3 without triggering the TypeError:
````
python -m venv spam
source spam/bin/activate
pip install sphinx
pip install regions
```

@bsipocz - Can you still reproduce the issue or have advice for @pdeiml that is facing it? Do we need to make a new `regions` release that contains the `astropy-helpers` fix?

**Comment by pdeiml** [comment]
Hello,
as @cdeil mentioned I ran into the same problem. But after full deletion of everything (gammapy, gamma-cat and gamma-cat conda environment) and reinstallation everything worked fine. I don't know what the problem is/ was.

**Comment by cdeil** [comment]
@pdeiml - Thanks for the feedback.

Let's see if the issue is still present on travis-ci and RTD (see #139) and if not I'll close this issue.

**Comment by cdeil** [comment]
I did manage to fix the issue by changing to `conda install regions` (or work around, not sure what the core of the issue was with the `pip install regions`):
* https://github.com/gammapy/gamma-cat/commit/0acbf8f1adf9c9b1d914ba8f44b1d6d258768d10
* https://travis-ci.org/gammapy/gamma-cat/builds/267476552

**Comment by cdeil** [comment]
After a few more tweaks (directly in `master`), the RTD build for gamma-cat works again:
* https://readthedocs.org/projects/gamma-cat/builds/5872498/
* (e.g. this new docs entry appears: http://gamma-cat.readthedocs.io/contribute/code.html#installation ).

Makes me 😄 .
