### ISSUE TITLE
How to handle sources with no TeGeV ID

### ISSUE THREAD

**Issue by GernotMaier** [gammapy/gamma-cat#136]
Not all TeV sources are apparently in TeGeV (is it still updated?)

I am looking for VER J1746-289 (from the 2016 GC ridge paper from VERITAS - 1602.08522 )

What do do?

**Comment by cdeil** [comment]
I think we should forget about TeGeV and TeVCat. Maybe leave as-is, i.e. link to their source ID where it exists.

Basically the TeVCat folks didn't want to collaborate, and the TeGeV folks did and were very friendly, but didn't have time to update their database (last updated 2015: http://www.asdc.asi.it/tgevcat/), and by now gamma-cat has more data (I think) and is set up in a community-maintainable way. There's probably quite a few lightcurves in TeGeV that we should ingest into gamma-cat if anyone ever has the time.

**Comment by GernotMaier** [comment]
OK - I simply add a new file in the input/sources directory.

It will be of course a mess when the TeGeV folks starts updating their catalogue...

**Comment by cdeil** [comment]
> It will be of course a mess when the TeGeV folks starts updating their catalogue...

We just have to work hard on gamma-cat like we're doing now, write a paper, and invite them and everyone to contribute here and stop their data collections.

:-)

Close issue?

**Comment by GernotMaier** [comment]
Close...
