### ISSUE TITLE
For light curves: add lifetime

### ISSUE THREAD

**Issue by GernotMaier** [gammapy/gamma-cat#143]
Would like to add the lifetime for each point in a light curve. Is that possible?

Reason:
lightcurve for 2012ApJ...746..151A (2012 M87 paper from HESS/MAGIC/VERITAS) is given as:

TIME           FLUX        FLUXERR       DURATION
MJD     cm^-2 s^-1     cm^-2 s^-1            MJD
53114.0    2.80811E-12    1.52328E-12      0.0202597
53114.9    1.85511E-12    1.02283E-12      0.0411745
53115.9   -2.14990E-13    8.09160E-13      0.0845801

**Comment by cdeil** [comment]
Adding extra columns or header keys is always fine.  Please add a line mentioning the key name you use here: https://github.com/gammapy/gamma-cat/blob/master/input/schemas/lightcurve-format.md

**Comment by GernotMaier** [comment]
Like this?

https://github.com/GernotMaier/gamma-cat/commit/77e30db67d45899defcc0fc2514bce905ed13506#diff-603d00da8218deb32f4fd92862a1a4d6

and this

https://github.com/GernotMaier/gamma-cat/commit/77e30db67d45899defcc0fc2514bce905ed13506#diff-3ae36088e230938c7dd078c40d3f15df

?

**Comment by cdeil** [comment]
I don't see the difference between the additions at the two links you put. They both look good (and identical) to me.

**Comment by GernotMaier** [comment]
No difference - they are the same. I thought there need to be one link per file (learned that github shows the differences in the revisions...)

Good - I need to clean up a few things - pull request will follow in the next days.

**Comment by cdeil** [comment]
OK. Also: you don't have to touch the Python scripts unless you want to. If you just do data entry and add definitions for new things to the schemas, then I'll adjust the Python scripts when merging.
