### ISSUE TITLE
A nice gamma-cat webpage

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#15]
I'm starting to work on the gamma-cat webpage, splitting it up into a landing page and one that lists all sources and all papers we have.
Possibly there should be other pages, I'm not sure yet.
- https://gammapy.github.io/gamma-cat/
- https://github.com/gammapy/gamma-cat/tree/master/docs

The point is, we have multiple pages, and it would be nice to have a navbar.

I see the following options to set this up:
1. Duplicate HTML code across the pages (for the navbar  and footer)
2. Use HTML imports (see [here](http://www.html5rocks.com/en/tutorials/webcomponents/imports/) and [here](https://github.com/webcomponents/webcomponentsjs) to make it work cross-browser
3. Use Python scripts and [Jinja](http://jinja.pocoo.org/docs/dev/) as a static website generator that fills in page-specific info into HTML page templates.

For now I'll start with 1, but I think it's worth considering option 2 and 3.

@vorugantia - When you get a chance, have a look and let me know what you think.

The main goal IMO is that those pages make it easy for us to search and navigate to any input file, and discover and download all files in `output/data`.
The nice HTML view of the data for end-users can then be on gamma-sky.net.

**Comment by cdeil** [comment]
A basic webpage is now in place:
https://gammapy.github.io/gamma-cat/

Can / should be extended to show more available data and help with data entry in many ways ...

**Comment by pdeiml** [comment]
I would like to close this issue. 
It is quite old and held very general and there has been done a lot on the webpage since 2016. For other issue according to the webpage we can open new issues in the future.
