### ISSUE TITLE
Dataset handling in collection.py

### ISSUE THREAD

**Issue by pdeiml** [gammapy/gamma-cat#174]
The handling of datasets is being written in collection.py in such a way that every dataset which is marked as "complete" is copied to docs/data.
Should we copy everything which means that files which are "incomplete" are copied as well.
If we choose the second way then we should add a line to the file in docs/data that this file is incomplete (can be handled in the DataSet class).

Should we rewrite the code which handles the light curve and sed files in analogy to this? 
I mean that the starting point is a index file created out of all info.yaml files and from that the copying to docs/data is handled.

@cdeil Please tell me your opinion about that.

**Comment by cdeil** [comment]
@pdeiml - Can you please do a PR to create an index file for `input` next? This will make everything else easier.

You could limit the PR to creating the input index file, or, if you have a lot of time in the coming days, you could try to start the big code restructure / delete for the later steps to use that index file. The goal is to have a PR which produces the same files in `output`, just change the scripts to work via the input index file.

**Comment by pdeiml** [comment]
Ok, then for now, I would add every file to output which is there. Hence, no distinction between "complete" and "incomplete" and neglecting the reviewed keyword.

I will leave a TODO remark where this distinction can be implemented in the future

**Comment by cdeil** [comment]
> Ok, then for now, I would add every file to output which is there. Hence, no distinction between "complete" and "incomplete" and neglecting the reviewed keyword.

I think this is a good way to do it. In the future, we might want to change our schema in `info.yaml` or introduce another place where we explicitly declare "release: yes/no" for resources, instead of relying on existing keys "complete" and "review". But that needs some thought / discussion how we want to maintain this ...

**Comment by pdeiml** [comment]
Should we rewrite the handling of lightcurve and seds in the same way as the datasets? Meaning that everything starts by scanning through the index-file which is produced by the info.yaml files?

**Comment by cdeil** [comment]
yes

**Comment by pdeiml** [comment]
@cdeil I think this issue can be closed, no?

**Comment by cdeil** [comment]
I didn't re-read the discussion in detail, but probably yes, no concrete action item left here.
