### ISSUE TITLE
Wrong hess name of source 42?

### ISSUE THREAD

**Issue by pdeiml** [gammapy/gamma-cat#189]
In 
https://www.mpi-hd.mpg.de/hfm/HESS/pages/home/sources/
source number 45 is called HESS J1018-589 but in 
https://github.com/gammapy/gamma-cat/blob/master/input/sources/tev-000045.yaml#L3
there it is called HESS J1018-589 A.

Why this A and should we change it to the "official" name in the source catalog of HESS?

**Comment by adonath** [comment]
Note that in a more recent analysis the source was split into two components `HESS J1018-589 A` and `HESS J1018-589 B` (see http://adsabs.harvard.edu/abs/2012A%26A...541A...5H and [HESS J1018-589 A](http://tevcat.uchicago.edu/?mode=1;id=237) and [HESS J1018-589 B](http://tevcat.uchicago.edu/?mode=1&showsrc=260) in the TeVCat catalog). I think the catalog on the MPIK web page is just outdated.

**Comment by pdeiml** [comment]
Ok, so we leave it as it is, right?

**Comment by adonath** [comment]
Yes, I checked it once again and it seems correct as it is now,
