### ISSUE TITLE
Absorped / de-absorped spectra

### ISSUE THREAD

**Issue by GernotMaier** [gammapy/gamma-cat#222]
For some papers, only de-absorpted spectra are available. I simply leave the information on the assumed EBL model in the comments.

Would it make sense to add a keyword to the SED files to indicate that the values are de-absorped? 

e.g. in 2011ApJ...727..129A, I have power law fits to the absorped spectra, but spectrals points for de-absorped spectra.

**Comment by cdeil** [comment]
Duplicate? #161

**Comment by GernotMaier** [comment]
Sorry - yes - close this one and keep #161
