### ISSUE TITLE
Bug in telescope names?

### ISSUE THREAD

**Issue by pdeiml** [gammapy/gamma-cat#232]
In https://github.com/gammapy/gamma-cat/blob/master/input/data/2003/2003ApJ...598..242A/info.yaml, the telescope is 'tibet' which is correct with respect to the paper.
But the telescope definitions in https://github.com/gammapy/gamma-cat/blob/master/input/schemas/basic_source_info.schema.yaml do not contain 'tibet'. Should we add it here?

**Comment by cdeil** [comment]
yip

**Comment by pdeiml** [comment]
I found 'tactic' as a second telescope which is not defined in https://github.com/gammapy/gamma-cat/blob/master/input/schemas/basic_source_info.schema.yaml.

Added both in https://github.com/gammapy/gamma-cat/pull/233

**Comment by cdeil** [comment]
Fixed by @pdeiml in #233 .
