### ISSUE TITLE
Add 2015arXiv150806311S - VERITAS Galactic center

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#24]
This is a reminder issue that we should add data from:

"VERITAS Observations of The Galactic Center Ridge"
http://adsabs.harvard.edu/abs/2015arXiv150806311S

**Comment by GernotMaier** [comment]
This data has been published in a journal article: https://arxiv.org/abs/1602.08522

and is in gammacat in 

https://github.com/gammapy/gamma-cat/tree/master/input/data/2016/2016ApJ...821..129A

I suggest that we do not include the data from the conference proceedings, but use the result from the refereed paper.

@cdeil: I suggest to close this issue.

**Comment by cdeil** [comment]
oké
