### ISSUE TITLE
Add data for HESS J1718-374, G349.7+0.2, 2015A%26A...574A.100H

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#40]
Folder already exists: https://github.com/gammapy/gamma-cat/tree/master/input/papers/2015/2015A%2526A...574A.100H
Paper: http://adsabs.harvard.edu/abs/2015A%26A...574A.100H
Spectral points: https://www.mpi-hd.mpg.de/hfm/HESS/pages/publications/auxiliary/auxinfo_SNRG349

**Comment by cdeil** [comment]
I'll do this one today.

**Comment by cdeil** [comment]
SED points added: https://github.com/gammapy/gamma-cat/blob/master/input/papers/2015/2015A%2526A...574A.100H/tev-000098.ecsv

I noticed that there's four upper limits at high energies in the paper, that are missing from:
https://www.mpi-hd.mpg.de/hfm/HESS/pages/publications/auxiliary/auxinfo_SNRG349
Emailing corresponding author now.

**Comment by cdeil** [comment]
Update: added https://github.com/gammapy/gamma-cat/blob/master/input/papers/2015/2015A%2526A...574A.100H/tev-000098.yaml

**Comment by cdeil** [comment]
Note to self: Diane Fernandez left science, Vincent Marandon and Cyril Trichard replied that they can't find the UL values any more.

So the 4 ULs should be read off the PDF Figure with a data picker.
Keeping this issue open as a reminder.

**Comment by pdeiml** [comment]
What is the status about this issue?
The sed and yaml files are added and what about the upper limit thing?
By the way: Do we already add upper limits to Gamma-Cat?

**Comment by pdeiml** [comment]
Added the upper limits in https://github.com/gammapy/gamma-cat/pull/228
Can be closed after merging https://github.com/gammapy/gamma-cat/pull/228
