### ISSUE TITLE
Add data for HESS J1831-098, 2011ICRC....7..244S

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#41]
Proceeding: http://adsabs.harvard.edu/abs/2011ICRC....7..244S
No paper exists on this source.
The proceeding contains spectral points in Figure 2.
Emailed Arache and Henning Nov 10, 2016 asking for the points.

**Comment by cdeil** [comment]
Spectral points from Arache Djannati-Atai via email on 25 Nov 2016:
https://gist.github.com/cdeil/4f38143712a452aeef859afe859d85e2

**Comment by cdeil** [comment]
@vorugantia - Do you have time for this in the coming days?

If not, no problem, @adonath or I could do it.

**Comment by vorugantia** [comment]
@cdeil - Yes, I can get started tomorrow.

**Comment by vorugantia** [comment]
See PR #59.

**Comment by cdeil** [comment]
Data entry for this paper finished in 5b5c441 .
Closing this issue now. 

Thanks @vorugantia for adding the SED!
