### ISSUE TITLE
Add missing HESS data for HGPS

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#43]
Info for these HESS / HGPS sources is missing in gamma-cat:

- [ ] HESS J1018-589A
- [ ] HESS J1018-589B
- [x] HESS J1554-550
- [ ] HESS J1641-462
- [ ] HESS J1800-240
- [x] HESS J1930+188

@adonath - I won't get to this today. This is a reminder issue for myself to do it tomorrow.

**Comment by cdeil** [comment]
Split out HESS J1930+188 to #51

**Comment by cdeil** [comment]
Split out HESS J1554-550 to #52

**Comment by adonath** [comment]
Superseded by https://github.com/gammapy/gamma-cat/blob/master/todo/todo_missing_hgps_sources.md
