### ISSUE TITLE
Add data from binary HESS J0632+057

### ISSUE THREAD

**Issue by GernotMaier** [gammapy/gamma-cat#50]
This is probably more a list of question from a new user than an issue.

Goal is to add all the data for HESS J0632+057  (for now mainly from the paper The Astrophysical Journal, 780:168 (14pp), 2014 January 10; http://adsabs.harvard.edu/abs/2014ApJ...780..168A)

**Lightcurve (table 1)**

following schemas/lightcurve-format.md , the fluxes and errors should be given in Crab units? Is this really a good choice? Which Crab spectrum should be assumed here? Wouldn't it be better to use usual units (photons/cm^2/s)?

Do I understand it correctly that upper flux limits are indicated by a '-1' for the flux error? Is there a possibility to give both flux+fluxerror and upper flux limit?

**Spectral results**

I have several spectral results for different periods, how can I add this? These are spectra for different orbits and different orbital phases. I am not sure how to indicate this in the data.

Same thing for the spectral points (SEDs), which I have for different orbital periods.

**Time periods vs orbital periods**

For binaries, we often combine data from several orbits and e.g. calculate average flux points for a given orbital period (e.g. the average flux at apastron, taken over multiple orbits). I guess the light curve format would have to be expanded to take this into account.

**Comment by cdeil** [comment]
> Do I understand it correctly that upper flux limits are indicated by a '-1' for the flux error? Is there a possibility to give both flux+fluxerror and upper flux limit?

@wegenmat has a big PR open to put all the existing LC data we have in a better format: #36.
@wegenmat - Could you please finish that up soon?

The idea is that we follow the SED format http://gamma-astro-data-formats.readthedocs.io/en/latest/results/flux_points/index.html as much as possible, and then hopefully soon someone writes up a LC spec.

---

> I have several spectral results for different periods, how can I add this?

For now, you should add one SED file in ECSV format per SED.

We've discussed recently that we should add `paper_info.yaml` for each paper, that declares which data is available. This would be the place where to put the relevant info. It doesn't exist yet, you could just add it in the folder in any format / organisation you want for now.

Having data in machine-readable format is already valuable. Having well-defined data model and formats will take longer and iteration / extension over the coming months.

---

> Time periods vs orbital periods
> I guess the light curve format would have to be expanded to take this into account.

Yes. Or keep the LC format simple and add another format on top that works for binaries, pulsars, ...

**Comment by cdeil** [comment]
Also, I forgot to say: yes, thanks, it would be great to have a first example dataset of phase-resolved or time-dependent spectra!

**Comment by GernotMaier** [comment]
Ok. That helps for a start.

Why are the light curves in a separate directory, while the SEDs and all the other information is in the corresponding paper directory?

**Comment by cdeil** [comment]
> Why are the light curves in a separate directory, while the SEDs and all the other information is in the corresponding paper directory?

This is one of the things I suggested in https://github.com/gammapy/gamma-cat/issues/9#issuecomment-257274913 to @wegenmat and he already improved in #36 .

As soon as that branch is merged, lightcurve data will be organised by paper in the `input` folder for  consistency / easy long-term maintenance.

**Comment by GernotMaier** [comment]
Could you point me to the discussion on the paper info file ( paper_info.yaml)? I couldn't find it.

**Comment by cdeil** [comment]
> Could you point me to the discussion on the paper info file ( paper_info.yaml)? I couldn't find it.

I don't think there's an issue on Github for it.

It's just something I wanted to do, to have something more declarative instead of gathering info via Python scripts. E.g. at the moment SEDs are collected like this:
https://github.com/gammapy/gamma-cat/blob/master/gammacat/sed.py#L241

Feel free to file issues or send pull requests any time.
At the moment I'm still doing it sporadially, as it's mostly me working on the files / scripts.

I will write docs for gamma-cat soon to describe now everything works, either the week before Christmas or first thing in January.

**Comment by cdeil** [comment]
Also, FYI: #36 was merged today, and I renamed all SED files to have a `-sed.ecsv` postfix.
`paper_id` was renamed to `reference_id`.
I.e. things are getting better ... but it's not very stable and existing README docs are outdated.

**Comment by GernotMaier** [comment]
Really complicated with the binaries (and I know that I am glacially slow in working on that):

From 2014ApJ...780..168A, I have for example spectra and SEDs for the same phases, but different orbits, but also for the exact same phase  values from HESS and VERITAS (it is a joint paper).

I would find the simplest solution to have in the paper.yaml file (in this case tev-000030.yaml) the following extensions

1. data fields for the orbital parameters (as each binary paper might use different values):

- name: spec_phase_min
  fmt:
  dtype: float32
  unit:
  description: phase range minimum (e.g. orbital or pulsar phase)
  latex:
- name: spec_phase_max
  fmt:
  dtype: float32
  unit:
  description: phase range maximum (e.g. orbital or pulsar phase)
  latex:

2. are several spectra in one file allowed? I was surprised that I couldn't find this for any of the other sources. If allowed, I would add a few more data fields to the spectra section: phase range, MJD range, instrument, string with the name of the corresponding sed file

3. several sed files, simply numbered (e.g.  tev-000030-sed-001.yaml) for each orbital phase/instrumental measurement

4. is repeated for the light curves, as e.g. this paper contains light curve measurements from two instruments, and we still would know which points are measured by which instrument

3/4 could also be done using single files only, if several SEDs per file are allowed (but how is then the connected done between spectra and SED?

I am still not sure what to to with the paper_info file.

**Comment by cdeil** [comment]
> are several spectra in one file allowed?

At the moment, no, we don't have that case.
I'm not sure it's easily doable and a good idea for ECSV.

If you think there's a good reason not to just use one ECSV file per input SED, we can look into whether it's possible to have multiple tables in one ECSV file, or use a second text-based input format that supports multiple tables in one file.

> if several SEDs per file are allowed (but how is then the connected done between spectra and SED? I am still not sure what to to with the paper_info file.

I'm also not sure yet. the `paper_info.yaml` file is just an idea.
There would be one such file, and it would point to multiple other small and simple YAML and ECSV files with the data.
Obviously one larger and more complex `tev-000030.yaml` file that contains multiple measurements is just as well possible.

---

What I've found with `gamma-cat` and any project really is that I don't get things (structure, organisation) right on the first try.
So we should just start and add more data, and as use-cases emerge we'll find better patterns to store and process the data, and will have to re-factor from time to time.

So for now, my advice would be that you add the data in whatever format you think best, with the main goal of having all data you care about available in a machine-readable format at all (i.e. YAML, ECSV for now).

OK?

**Comment by GernotMaier** [comment]
Agree. This is the reason why I've started to add all the data, even if the parser do not work correctly with them. 

Right now the spectral fits are in the all in the yaml file (e.g.  https://github.com/GernotMaier/gamma-cat/blob/3ea707cf54e129a0ee5d057db5939e663446d34d/input/data/2014
/2014ApJ...780..168A/tev-000030.yaml)

Two solutions come to my mind:

-  have the possibility to add a ...-spec.ecvs file, with a table with all the data from the spectral fits.
- add the spectral fit data to the top of the ...-sed.ecvs file: this would have the advantage that the SED data and the fit is in the same place.

**Comment by cdeil** [comment]
I think my suggestion would be to put multiple YAML files.
And my second choice one a single YAML file with a list of of ordered dict of spectrum sections.
And only then the two options you mention.

But as I said ... put what you like best ... I'm OK to merge for now whatever you prefer.

**Comment by GernotMaier** [comment]
Agree. That is actually the simplest solution. I've added now multiple yaml files, each containing the spectral fits from one orbital period.

**Comment by cdeil** [comment]
@GernotMaier - Is this done?

If yes, could you please close the issue?
If no, could you please summarise what is missing?

**Comment by GernotMaier** [comment]
sorry - forgot to close this issue - this is completed.
