### ISSUE TITLE
Add data: VERITAS 2010 G54.1+0.3 2010ApJ...719L..69A

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#51]
Add data: VERITAS 2010 G54.1+0.3 2010ApJ...719L..69A
aka HESS J1930+188

Source: https://github.com/gammapy/gamma-cat/blob/master/input/sources/tev-000136.yaml
Paper on ADS: http://adsabs.harvard.edu/abs/2010ApJ...719L..69A
Paper data: https://github.com/gammapy/gamma-cat/tree/master/input/papers/2010/2010ApJ...719L..69A

YAML file is in gamma-cat.

Spectral points aren't available here: http://veritas.sao.arizona.edu/veritas-science/veritas-results-mainmenu-72/235-could-we-put-in-a-journal-reference-here-
Emailed [Ester Aliu](https://www.nevis.columbia.edu/~ealiu/KK/Welcome.html) just now asking for spectral points.

**Comment by cdeil** [comment]
@gernotmaier - Do you know if there's any chance to get this VERITAS SED data?
Is it available or is there someone I could contact? (no answer from corresponding author on this one so far).

I'm mostly interested in the Galactic sources that both VERITAS and HESS see, for the HESS GPS checks. I.e. J1930 here, but also e.g. the recent J1943 info: https://arxiv.org/abs/1610.05799

**Comment by GernotMaier** [comment]
For VER J1930+188 (Fig 2) in 2010ApJ...719L..69A:

0.31071 TeV  1.098e-11 +- 5.66021e-12
0.49244 TeV  4.23584e-12 +- 1.43402e-12
0.78047 TeV  1.11824e-12 +- 4.53778e-13
1.23697 TeV  6.16714e-13 +- 1.65801e-13
1.96046 TeV  <2.89359e-13
3.10712 TeV  3.94788e-14 +- 2.11699e-14
4.92446 TeV  <3.80571e-14

(not cutting here on the number of valid digits)
Corresponding author left VERITAS.

I don't find the data for J1943, but Karlen should be around and answer to emails.

**Comment by cdeil** [comment]
@GernotMaier - Thanks!

J1930 SED added to gamma-cat in df3d24c
This issue is done. Closing it now.

Will open a new one for J1943.
