### ISSUE TITLE
Fill gamma-cat SED info from output folder

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#57]
I think currently the SED info in `gamma-cat` is filled from the input SED folder.

It would be better to fill it from the `docs/data` output folder, to make sure it's clean and consistent with the separate SEDs we give to users.

@adonath - Can you do the change?
(if no, assign back to me and I'll do it next week)

**Comment by adonath** [comment]
As a quick fix I added an option to `SEDList.read()` (see [here](https://github.com/gammapy/gamma-cat/blob/master/gammacat/sed.py#L239)). Longterm it might be better to use the `OutputDataReader` class instead...

**Comment by cdeil** [comment]
Changing back to `folder="input"` for `InputData`, so that `./make.py all` and `./make.py check` work again.

Possible solution: set `folder="output"` only in catalog generation,
- either just for SEDs for now
- or for all files, and copy YAML over to output for now (and fix formatting later)

**Comment by cdeil** [comment]
@vorugantia today ran into this issue.

Trying to plot the spectral points for Vela X currently doesn't work:
http://nbviewer.jupyter.org/github/vorugantia/scienceresearch11/blob/master/notebooks/Task%202.ipynb

The reason is that the input file only has symmetric flux errors filled:
https://github.com/gammapy/gamma-cat/blob/3565b3dbc2dd5936f6164d88fbf5db6f31f737ef/input/data/2012/2012A%2526A...548A..38A/tev-000037-sed.ecsv
and the way the catalog is filled this leads to no flux point error info and then no flux points plotted.

To reproduce:
```python
from gammapy.catalog import SourceCatalogGammaCat
cat = SourceCatalogGammaCat()
source = cat['Vela X']
source.flux_points.table # no flux error filled
source.data['sed_dnde_err'] # only NaN values
```

If the SED file from the output folder were used, this problem would be resolved:
https://github.com/gammapy/gamma-cat/blob/master/docs/data/sources/000037/gammacat_000037_2012A%2526A...548A..38A_sed.ecsv

In addition, probably the SED plotting method in Gammapy should be changed, so that at least points show up for SEDs where no flux error info (but flux values) are available.

**Comment by cdeil** [comment]
I finally got around to implementing this in 4a57197 .

This change does fix the spectral points plotted for 18 sources:
https://github.com/cdeil/gamma-cat-status/commit/40bc6469d0e129240980cd8d13233c4979cd6621
