### ISSUE TITLE
Add data on HESS J1943+213 from VERITAS 2016arXiv161005799S

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#58]
Source: https://github.com/gammapy/gamma-cat/blob/master/input/sources/tev-000137.yaml
Paper:  http://adsabs.harvard.edu/abs/2016arXiv161005799S

Emailed corresponding author asking for SED points in Figure 2 just now.

**Comment by KarlenS** [comment]
Here are the spectral points for HESS J1943+213.

E_ref[TeV] dN/dE[cm-2 s-1 TeV-1] dN/dE_err
0.2105 5.65e-11 9.32e-12
0.2973 2.48e-11 3.15e-12
0.42   7.15e-12 1.21e-12
0.5933 3.2e-12 5.47e-13
0.838  1.46e-12 2.64e-13
1.184  3.52e-13 1.13e-13
1.672  2.04e-13 6.33e-14

**Comment by cdeil** [comment]
@KarlenS - Thank you!

Added in a2a447c .
Data for this paper is here: https://github.com/gammapy/gamma-cat/tree/master/input/data/2016/2016arXiv161005799S

If you also have the LC data from Fig 3 available, I could add that as well.

**Comment by KarlenS** [comment]
And the LC data from Fig3 (weekly time bins):

MJD[days] Flux[cm-2 s-1] Flux_err[cm-2 s-1]
56807.411655 3.623e-12 1.164e-12
56814.411655 4.172e-12 1.372e-12
56828.411655 6.895e-12 1.555e-12
56835.411655 6.421e-12 8.308e-13
56842.411655 7.156e-12 1.119e-12
57129.411655 1.999e-12 5.462e-12
57143.411655 9.788e-14 3.135e-12
57164.411655 8.547e-12 7.043e-12
57192.411655 3.166e-13 2.013e-12
57283.411655 5.269e-12 1.681e-12
57297.411655 5.111e-12 2.134e-12
57325.411655 1.366e-11 4.86e-12
57332.411655 4.478e-12 2.195e-12

**Comment by cdeil** [comment]
@KarlenS - Thanks for the lightcurve data!

Added in 261a5f7 .

Is it correct that that fluxes given are above 200 GeV?

**Comment by KarlenS** [comment]
Yup. That's correct.
