### ISSUE TITLE
Remove source_name key in input files

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#86]
Suggestion by @pdeiml - At the moment we sometimes put `source_name` in input files, and sometimes not.  The idea is that only `source_id` is used, and than `source_name` or `common_name` is only added to help with not getting confused about which file is for which source.

But putting names is problematic, it leads to inconsistencies between names used.
Options are:

a. Remove all `source_name` or `common_name` entries in input files.
b. Keep `common_name`, but document that it's optional and for convenience.

I'd like to sleep on it, but at the moment I'm leaning towards option a.

**Comment by pdeiml** [comment]
Just for completeness:
We decided to use option a.

**Comment by adonath** [comment]
@cdeil @pdeiml Where else then is the information on `common_name` and other source names etc. stored?

**Comment by cdeil** [comment]
The basic source info for a given `source_id` is in the files in `input/sources`.
So the idea is to only keep `source_id` in the files in `input/data`, and then only have names and such in one location, the files in `input/sources`.

One thing I do think we should allow is to have comments in the input files, e.g. in cases where there's multiple sources in one paper, and it helps with data input and review to have comments explaining which source data is entered here.

**Comment by adonath** [comment]
@cdeil Thanks for the clarification. :+1: for this change!

**Comment by cdeil** [comment]
It's quick to find all cases via `ack 'source' input/data` and do the clean-up.

@pdeiml - You or me?

**Comment by pdeiml** [comment]
@cdeil I can do it. Either today in the afternoon or on Monday, I will have time for that.
I think it is not an urgent thing.

**Comment by cdeil** [comment]
> @cdeil I can do it. Either today in the afternoon or on Monday, I will have time for that.
I think it is not an urgent thing.

Thanks! Not urgent at all.
I just wanted to avoid you and me starting the same thing.
For this, let's use the "assignee" field on Github, i.e. assign issues to the one planning to take care of it.
So in this case, I'm assigning it to you, and you can just do it whenever you have time.

**Comment by cdeil** [comment]
Implemented by @pdeiml in #95.
Closing now.
