### ISSUE TITLE
Make the name of the xml parameters compatible with ctools

### ISSUE THREAD

**Issue by robertazanin** [gammapy/gamma-cat#94]
@cdeil 
Spectral models:
ExpCutoff --> ExponentialCutoffPowerLaw
Cutoff --> CutoffEnergy
Scale --> PivotEnergy

Spatial models 
Gauss --> RadialGaussian
Shell --> RadialShell
Point --> PointSource
GLON/GLAT --> RA/DEC

General 
now what we have is: 
<parameter name="Index" value="-2.4600000381469727" unit=""/>
should be:
<parameter scale="1.0"   name="Index"      min="-5.0"  max="+5.0"      value="-2.0" free="1"/>
no unit is forseen and free, min and max are mandatory

Then there is this PowerLaw2 that it is not foreseen:
<source name="HESS J1614-518" type="ExtendedSource">
    <spectrum type="PowerLaw2">
        <parameter name="Integral" value="5.780000089661286e-11" unit="1 / (cm2 s)"/>
        <parameter name="Index" value="-2.4600000381469727" unit=""/>
        <parameter name="LowerLimit" value="0.20000000298023224" unit="TeV"/>
        <parameter name="UpperLimit" value="10000000000.0" unit="TeV"/>
    </spectrum>

This is what I have spotted so far

**Comment by cdeil** [comment]
I've moved these comments to https://github.com/gammasky/cta-dc/issues/6#issuecomment-287028705 and  I'm closing this issue now.
This is something I will address just by changing the scripts in the cta-dc repo, not here in gamma-cat, so I prefer to have it there.
