### ISSUE TITLE
wrong prefactor for HESS J1825

### ISSUE THREAD

**Issue by robertazanin** [gammapy/gamma-cat#97]
Wrong prefactor in 2006A&A...460..365A

**Comment by robertazanin** [comment]
@cdeil

**Comment by cdeil** [comment]
@robertazanin - Why do you think it's wrong?

---

I had a look and this is my current understanding:
* Current spectral parameters in https://github.com/gammapy/gamma-cat/blob/master/input/data/2006/2006A%2526A...460..365A/tev-000118.yaml are this:
```
spec:
  type: ecpl
  # Results taken from Table 1 ecpl model
  # TODO: I'm not sure the norm is entered correctly!?
  #       Have to check ECPL parametrization exactly.
  norm: {val: 21.0, err: 0.5}
  index: {val: 2.26, err: 0.03}
  ecut: {val: 24.8, err: 7.2}
  ref: 1
  theta: 0.8d
  erange: {min: 0.27}
```
* So indeed there's a TODO that we should check if the prefactor is correct.
* ECPL formula at https://gammapy.readthedocs.io/en/latest/api/gammapy.spectrum.models.ExponentialCutoffPowerLaw.html and in table 1 in the paper (https://ui.adsabs.harvard.edu/#abs/2006A&A...460..365A) look identical to me
* Parameters in gamma-cat FITS catalog seem to be OK, i.e. as expected when I access them via
```python
>>> from gammapy.catalog import SourceCatalogGammaCat
>>> cat = SourceCatalogGammaCat()
>>> source = cat['HESS J1825-137']
>>> print(source.spectral_model)
ExponentialCutoffPowerLaw
ParameterList
Parameter(name='index', value=2.259999990463257, unit=Unit(dimensionless), min=0, max=None, frozen=False)
Parameter(name='amplitude', value=2.100000034976901e-11, unit=Unit("1 / (cm2 s TeV)"), min=0, max=None, frozen=False)
Parameter(name='reference', value=1.0, unit=Unit("TeV"), min=None, max=None, frozen=True)
Parameter(name='lambda_', value=0.040322581885632605, unit=Unit("1 / TeV"), min=0, max=None, frozen=False)
```
* Plotted spectrum looks OK to me, i.e. spectral model consistent with spectral points: https://github.com/cdeil/gamma-cat-status/blob/master/sed_png/source_000118.png (but it can be hard to judge small issues with ECPL norm).

@robertazanin - Can you please have a closer look and let me know if you agree the current flux norm parameter is OK? Or if no, let me know what you think it should be.

**Comment by cdeil** [comment]
I've discussed this with @robertazanin and we both agree the current parameters are OK.
Removed the TODO from the input file in a277e99 .
Closing this issue now.
