### ISSUE TITLE
Add VERITAS IC 443 2015arXiv151201911H

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#98]
* IC 443 (gammacat source_id=29)
* YAML added: `input/data/2015/2015arXiv151201911H/tev-000029.yaml`
* VERITAS ICRC 2015 proceeding: http://adsabs.harvard.edu/abs/2015arXiv151201911H
* For spectral points, contactad the author on March 31, 2017. Waiting for reply.

**Comment by cdeil** [comment]
@GernotMaier - Can you get your hands on the spectral points for IC 443 from http://adsabs.harvard.edu/abs/2015ICRC...34..875H ?

**Comment by cdeil** [comment]
After #140 I re-ran the scripts to update the auto-generated files and made a few more small fixes in `master`.

There's one remaining problem I see here:
https://github.com/cdeil/gamma-cat-status/commit/d9da0e138502805068eca039047936eccebf99bd#diff-ae36e7e6fccd700ddf695565bb971cff

The spectral points from `input/data/2009/2009ApJ...698L.133A/tev-000029-sed.ecsv` are all below the spectral model from `input/data/2009/2009ApJ...698L.133A/tev-000029.yaml`. Looking at the numbers from the paper to me the spectral model parameters seem correct: http://iopscience.iop.org/article/10.1088/0004-637X/698/2/L133/meta#apjl315544s3
@GernotMaier - Can you please have a look and try to fix this?

Also, the spectral model from `input/data/2015/2015arXiv151201911H/tev-000029.yaml` seems very different / inconsistent with the spectral model from `2009ApJ...698L.133A`. Another data entry bug?

**Comment by cdeil** [comment]
Update: I think there is still an issue with the spectra for this source. See https://github.com/cdeil/gamma-cat-status/blob/cc3084fc9b43933a93203275eed7385d322efb82/notebooks/data_collection_example.ipynb .

**Comment by GernotMaier** [comment]
Checked this and found out that the normalisation energy in the proceedings is very likely wrong: e_ref should be 1 TeV, and not 550 GeV .

I leave this issue open until I get confirmation from the corresponding author.

**Comment by GernotMaier** [comment]
Close this now - received confirmation that the normalisation energy is 1 TeV and fixed this in the yaml file.

**Comment by cdeil** [comment]
Fixed by @GernotMaier in #209.
