### ISSUE TITLE
Add VERITAS Tycho 2017arXiv170106740V

### ISSUE THREAD

**Issue by cdeil** [gammapy/gamma-cat#99]
* Tycho SNR (gammacat source_id=3)
* YAML added: `input/data/2017/2017arXiv170106740V/tev-000003.yaml`
* Paper: http://adsabs.harvard.edu/abs/2017arXiv170106740V
* For spectral points, contacted the author Nahee Park on March 31, 2017. Waiting for reply.

**Comment by GernotMaier** [comment]
This issue can be closed - these data is in 2017ApJ...836...23A

**Comment by cdeil** [comment]
For the record: I've removed the old file in https://github.com/gammapy/gamma-cat/commit/2060d95ac582c7dd866e32238c89d5e2895a7468

**Comment by cdeil** [comment]
@GernotMaier - The last upper limit point for Tycho is unreasonably low:
https://github.com/cdeil/gamma-cat-status/commit/4f4bf6ffc950a2214f01993ea119e08f20003088#diff-e496a30d8d81ccc19b5e888cde3c688d

This comment suggests it should be at `9.4` and not `7.5` TeV:
https://github.com/gammapy/gamma-cat/blob/master/input/data/2017/2017ApJ...836...23A/tev-000003-sed.ecsv#L18

That would make it a little more reasonable, but still probably much too low.

I don't see such a low UL in the paper:
https://arxiv.org/pdf/1701.06740.pdf

@GernotMaier - Please double-check and fix this UL.

**Comment by GernotMaier** [comment]
The UL was 1.e-4 wrong - I've corrected it. The UL calculated between 7.5 and 75 TeV, but draw in the paper at 9.4 TeV. I've changed the reference energy now to 9.4 TeV.

Ok?

**Comment by cdeil** [comment]
Perfect. 

For reference, fix is here: https://github.com/gammapy/gamma-cat/pull/137/commits/ea9e3ab533a24e5eb94ff7579affc1de538c7578
